# Generated by Django 5.0.6 on 2024-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='titolo',
            field=models.CharField(max_length=30),
        ),
    ]
