# Generated by Django 5.0.6 on 2024-05-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_titolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='titolo',
            field=models.CharField(max_length=50),
        ),
    ]
