# Generated by Django 5.0.6 on 2024-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_titolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='titolo',
        ),
        migrations.AddField(
            model_name='store',
            name='artista',
            field=models.CharField(default='Select an option: 1', max_length=30),
            preserve_default=False,
        ),
    ]
