# Generated by Django 5.0.6 on 2024-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_store_titolo_store_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='titolo',
            field=models.CharField(default='titolo', max_length=100),
            preserve_default=False,
        ),
    ]
